### ISSUE TITLE
What is the addendum file for?

### ISSUE THREAD

**Issue by trosel** [Shavian-info/readlex#1]
Just wondering what this file is for exactly? Is it for Brand names and common abbreviations like SMS?

**Comment by Shavian-info** [comment]
Both readlex.dict and addendum.dict can be used with Dave Coffin's transliteration scripts at [Dechifro.org](https://www.dechifro.org/shavian/) if you would prefer to follow ReadLex spellings. The file 'addendum.dict' is for spellings that I don't propose to add to the ReadLex, such as names and a lot of initialisms, for which 'standard' RP pronunciations are almost impossible to find (names are inherently personal). There are, of course, some legacy names and initialisms in the ReadLex which I hope to clean up over time.
