### ISSUE TITLE
Some technical words

### ISSUE THREAD

**Issue by JapanYoshi** [Shavian-info/readlex#10]
I've discovered that these words were missing from the lexicon while transl(iter)ating [Godot engine](https://hosted.weblate.org/translate/godot-engine/godot/en-Shaw).
```
operand	𐑪𐑐𐑼𐑨𐑯𐑛 (values to which an operation is applied to)
operands	𐑪𐑐𐑼𐑨𐑯𐑛𐑟
Bezier	𐑚𐑧𐑟𐑦𐑱 (Bézier curve: a type of mathematical curve)
Bézier	𐑚𐑧𐑟𐑦𐑱
interp	𐑦𐑯𐑑𐑻𐑐 (short for interpolation)
```

**Comment by Shavian-info** [comment]
Thanks for these suggestions. I will add them when I can, but may not have a chance for about a week or so.

**Comment by Shavian-info** [comment]
Added. Sorry for the delay.
