### ISSUE TITLE
“drawer”

### ISSUE THREAD

**Issue by trosel** [Shavian-info/readlex#13]
draw | 𐑛𐑮𐑷 | VVI | drɔː | 4109
-- | -- | -- | -- | --
drawer | 𐑛𐑮𐑹

i think there might need to be a word for a person that draws. 𐑛𐑮𐑷𐑼?

**Comment by JapanYoshi** [comment]
I don't think "drawer" could mean "a person that draws" except in an ironic meme.

**Comment by Shavian-info** [comment]
It would be useful to know the frequency of 'drawer' meaning 'person who draws'. Adding it to the ReadLex would mean that every time the word 'drawer' (as in furniture) appears in a text, it would become a heteronym that needs to be resolved manually. Given I have never seen the word 'drawer' outside legal texts, as in a person who draws a cheque, I wonder if it would actually help to add it or just make more work.

**Comment by trosel** [comment]
> Adding it to the ReadLex would mean that every time the word 'drawer' (as in furniture) appears in a text, it would become a heteronym that needs to be resolved manually

I think this should only be a consideration if the primary usage of the dictionary is in crude latin-to-shavian transliteration programs. If it is meant to be a standalone dictionary, "a person that draws" is indeed a word (and it is pronounced differently from the furniture as well).

**Comment by Shavian-info** [comment]
@trosel Agreed, it is a legitimate heteronym. I've added it.
