### ISSUE TITLE
‘humph’

### ISSUE THREAD

**Issue by mwgamera** [Shavian-info/readlex#14]
I think the transcription of ‘humph’ is incorrect:
```
humph	𐑣𐑳𐑥𐑐𐑓	ITJ	hʌmpf	0
```
It probably should be:
```
humph	𐑣𐑳𐑥𐑓	ITJ	hʌmf	0
```
Cambridge Pronouncing Dictionary (17th ed.) gives ‘m̥m, hə̃h, hʌmf’ mentioning the falling pitch in an additional note rather than in IPA, and saying that ‘the transcriptions reflect a wide range of possible pronunciations’.

Other dictionaries sometimes have weaker /həmf/ instead or in addition to /hʌmf/ ([AHD](https://ahdictionary.com/word/search.html?q=humph), [Oxford Learner's](https://www.oxfordlearnersdictionaries.com/pronunciation/english/humph), [Macmillan](https://www.macmillandictionary.com/dictionary/british/humph)). 
There are some that give /hʌmpf/ ([CUBE](http://cube.elte.hu/index.pl?s=humph&gimson=on), [M-W](https://www.merriam-webster.com/dictionary/humph)). My understanding is that there is some difference between the nasal noise that is difficult to fit into phonemic inventory and the onomatopoeic word derived from it and used to denote that noise (and also as a verb). The former may differ from ‘hmm’ only by the amount of aspiration and pitch contour in some realizations like [m̥m]; the latter may be pronounced with a fricative at the end, and some people even put a labial stop in there. But there is no /p/ in Cambridge.

**Comment by JapanYoshi** [comment]
I'm in favor of 𐑣-𐑩-𐑥-𐑓, although I've dropped the 𐑩 in a comic transcription before.

**Comment by Shavian-info** [comment]
I think many interjections are so subjective that I don't worry too much about them. Use whatever makes sense for you in the context. They are at best an imperfect adaptation of the Latin alphabet to non-phonemic utterances. Shavian could probably develop its own interjections. Given this, I might shift them out of the ReadLex to the addendum.dict document to avoid giving any impression of an 'official' spelling.

**Comment by mwgamera** [comment]
I think it's similar to what happens with acronyms where pronunciation reveals their ties with Latin script. It is, however, a part of both the spoken and written language even if some would refuse to call it a word. Naturally, Shavian should develop its own spellings for interjections, not completely new interjections. That the noise itself relies on features that are non-phonemic to be distinguished from completely different noises is all the more reason why a recognizable spelling is desired. Obviously, some informal variations like ‘hmph’ (and its Shavian counterpart ‘𐑣𐑥𐑓’) are possible, but not ‘hmm’, ‘mh’, ‘hun’, or ‘huh’, for example, as these would be misinterpreted.

Moving it to addendum might be okay for now, but I would still drop that ‹𐑐›.

**Comment by Shavian-info** [comment]
Agreed, 'humph' is now '𐑣𐑳𐑥𐑓'.
