### ISSUE TITLE
ombre: 𐑪𐑥𐑚𐑼 or 𐑪𐑥𐑚𐑮𐑱

### ISSUE THREAD

**Issue by JapanYoshi** [Shavian-info/readlex#15]
I came across the word "quadrille" while using the automatic transcription script for Firefox, so I looked up its definition on Merriam-Webster, on which one of the definitions had the word "ombre". But its dictionary transcribed it as 𐑴𐑥𐑚𐑮𐑧, which just didn't add up to me.

According to [Merriam-Webster's pronunciation guide](https://www.merriam-webster.com/dictionary/ombre) and [Collins Dictionary](https://www.collinsdictionary.com/dictionary/english/ombre), it should be 𐑪𐑥𐑚𐑼; Wiktionary accepts both, but Merriam-Webster uses 𐑪𐑥𐑚𐑮𐑱 if spelled with `é`.

**Comment by Shavian-info** [comment]
I'll add the noun as 𐑪𐑥𐑚𐑼, following the Cambridge Pronouncing Dictionary. Ombré, the adjective, should be 𐑪𐑥𐑚𐑮𐑱.

**Comment by Shavian-info** [comment]
I've added 'ombre' in its various senses.
