### ISSUE TITLE
issue with "have to" causing duplication errors when converting from Latin to Shavian

### ISSUE THREAD

**Issue by peter-got-github** [Shavian-info/readlex#19]
Input of Latin "you have to" results in "𐑿 𐑣𐑨𐑝𐑨𐑓 𐑣𐑨𐑝 𐑑" 

Input of Latin "I can't believe apples have to do this" results in "𐑲 𐑒𐑭𐑯𐑑 𐑚𐑦𐑤𐑰𐑝 𐑨𐑐𐑩𐑤𐑟 𐑣𐑨𐑝𐑨𐑓 𐑒𐑭𐑯𐑑 𐑚𐑦𐑤𐑰𐑝 𐑨𐑐𐑩𐑤𐑟 𐑣𐑨𐑝 𐑑 𐑛𐑵 𐑞𐑦𐑕"

Inputting "have" outside of "have to," for instance "I have an apple to eat," doesn't make unexpected results.

**Comment by Shavian-info** [comment]
Thanks @peter-got-github. It should be fixed now. If it works for you, could you close the issue?
