### ISSUE TITLE
"Hallucinosis"

### ISSUE THREAD

**Issue by csditchfield** [Shavian-info/readlex#20]
There are a number of missing words relating to hallucinosis.
Based on the existing encoding of `hallucinogenic → 𐑣𐑩𐑤𐑵𐑕𐑦𐑯𐑩𐑡𐑧𐑯𐑦𐑒` I would recommend the following:
```
hallucinate   -> 𐑣𐑩𐑤𐑵𐑕𐑦𐑯𐑱𐑑
hallucinates  -> 𐑣𐑩𐑤𐑵𐑕𐑦𐑯𐑱𐑑𐑕
hallucinating -> 𐑣𐑩𐑤𐑵𐑕𐑦𐑯𐑱𐑑𐑦𐑙 
hallucinative -> 𐑣𐑩𐑤𐑵𐑕𐑦𐑯𐑩𐑑𐑦𐑝
hallucinant   -> 𐑣𐑩𐑤𐑵𐑕𐑦𐑯𐑩𐑯𐑑
hallucinosis  -> 𐑣𐑩𐑤𐑵𐑕𐑦𐑯𐑴𐑕𐑦𐑕
hallucinogen  -> 𐑣𐑩𐑤𐑵𐑕𐑦𐑯𐑩𐑡𐑧𐑯
```
Collins would agree with the first 𐑦, but Merriam-Webster would substitute 𐑩.

**Comment by Shavian-info** [comment]
Thanks @csditchfield. I've added these words and a couple more, see the [hallucin* - ReadLex](https://readlex.pythonanywhere.com/dictionary/hallucin%2A)
