### ISSUE TITLE
word "appropriate" failed to convert

### ISSUE THREAD

**Issue by peter-got-github** [Shavian-info/readlex#21]
With input "I will use my favorite contraction when appropriate", the converter output "𐑲 𐑢𐑦𐑤 𐑿𐑟 𐑥𐑲 𐑓𐑱𐑝𐑼𐑦𐑑 𐑒𐑩𐑯𐑑𐑮𐑨𐑒𐑖𐑩𐑯 𐑢𐑧𐑯 appropriate." Assuming that the converter couldn't decide between multiple pronunciations in this case, I would expect it to render both options separated by a | , as described on the output page.

**Comment by Shavian-info** [comment]
I think I've fixed this now. Could you test it? if it all works as expected, please feel free to close the issue.
