### ISSUE TITLE
Some more words

### ISSUE THREAD

**Issue by JapanYoshi** [Shavian-info/readlex#27]
𐑺𐑚𐑨𐑜	airbag
    𐑺𐑚𐑨𐑜𐑟	airbags
    𐑭𐑡𐑦𐑟	ajis	(ReadLex only has singular)
    𐑨𐑯𐑑𐑦𐑓𐑭	antifa	(alternate pronunciation)
    𐑚𐑦𐑥𐑿𐑟	bemuse	(ReadLex only has "bemused")
    𐑚𐑤𐑨𐑥	blam
    𐑚𐑤𐑨𐑥𐑟	blams
    𐑚𐑤𐑨𐑥𐑦𐑙	blamming
    𐑚𐑤𐑨𐑥𐑛	blammed
    𐑗𐑰𐑑𐑼	cheater	(ReadLex only has "windcheater(s)")
    𐑗𐑰𐑑𐑼𐑟	cheaters
    𐑒𐑩𐑤𐑨𐑚𐑟	collabs
    𐑽𐑤𐑴𐑚	earlobe
    𐑽𐑤𐑴𐑚𐑟	earlobes
    𐑓𐑦𐑤𐑱	filet	(US spelling & pronunciation)
    𐑓𐑦𐑤𐑱𐑛	fileted	(US spelling & pronunciation)
    𐑓𐑦𐑤𐑱𐑦𐑙	fileting	(US spelling & pronunciation)
    𐑓𐑦𐑤𐑱𐑟	filets	(US spelling & pronunciation)
    𐑣𐑳𐑥𐑩𐑕	hummus	(US)
    𐑣𐑫𐑥𐑩𐑕	hummus	(UK)
    𐑡𐑨𐑒𐑩𐑤𐑴𐑐	jackalope
    𐑡𐑨𐑒𐑩𐑤𐑴𐑐𐑕	jackalopes
    𐑒𐑻𐑯	kern
    𐑒𐑻𐑯𐑦𐑙	kerning
    𐑒𐑦𐑚𐑦𐑑𐑕	kibitz
    𐑒𐑦𐑚𐑦𐑑𐑕𐑼	kibitzer
    𐑥𐑨𐑒𐑕𐑑	maxed	
    𐑥𐑿𐑑𐑱𐑑	mutate	
    𐑥𐑿𐑑𐑱𐑑𐑩𐑛	mutated	
    𐑥𐑿𐑑𐑱𐑑𐑕	mutates	
    𐑥𐑿𐑑𐑱𐑑𐑦𐑙	mutating	
    𐑐𐑧𐑛𐑦	pedi	
    𐑐𐑮𐑧𐑜𐑴	preggo	
    𐑖𐑱𐑛𐑼	shader	
    𐑖𐑱𐑛𐑼𐑟	shaders	
    𐑖𐑲𐑯𐑛	shined	
    𐑕𐑦𐑑𐑦𐑯	sit-in	
    𐑕𐑦𐑑𐑦𐑯𐑟	sit-ins
    𐑕𐑦𐑑𐑳𐑐	sit-up
    𐑕𐑦𐑑𐑳𐑐𐑕	sit-ups
    𐑕𐑴𐑛𐑩𐑟	sodas	
    𐑕𐑪𐑛𐑼	solder	(US)
    𐑕𐑪𐑛𐑼𐑛	soldered	(US)
    𐑕𐑪𐑛𐑼𐑦𐑙	soldering	(US)
    𐑕𐑪𐑛𐑼𐑟	solders	(US)
    𐑕𐑳𐑥𐑢𐑳𐑯𐑟	someone's
    𐑑𐑮𐑱𐑯𐑮𐑧𐑒	trainwreck
    𐑑𐑮𐑱𐑯𐑮𐑧𐑒𐑕	trainwrecks
    𐑿𐑯𐑦𐑑𐑸𐑛	unitard	
    𐑿𐑯𐑦𐑑𐑸𐑛𐑟	unitards	
    𐑢𐑦𐑐𐑤𐑨𐑖	whiplash	
    𐑢𐑦𐑐𐑤𐑨𐑖𐑑	whiplashed
    𐑢𐑦𐑐𐑤𐑨𐑖𐑩𐑟	whiplashes
    𐑢𐑦𐑐𐑤𐑨𐑖𐑦𐑙	whiplashing
    𐑢𐑦𐑡𐑩𐑑	widget	
    𐑢𐑦𐑡𐑩𐑑𐑕	widgets	
    𐑮𐑪𐑙𐑯𐑩𐑕	wrongness	
    𐑟𐑧𐑯𐑟	zens	
    𐑟𐑱𐑑𐑩	zeta	(US)
    𐑟𐑰𐑑𐑩	zeta	(UK)
    𐑟𐑱𐑑𐑩𐑟	zetas	(US)
    𐑟𐑰𐑑𐑩𐑟	zetas	(UK)

**Comment by Shavian-info** [comment]
Okay, thanks. I'll add these when I next do some updates to the wordlist.
