### ISSUE TITLE
Clarification on the readlex methodology regarding yods

### ISSUE THREAD

**Issue by trosel** [Shavian-info/readlex#29]
I was thinking of the word DUNE and how there are roughly three different pronunciations for this word:

𐑛𐑿𐑯, 𐑛𐑵𐑯, and 𐑡𐑵𐑯 (see [this video](https://www.youtube.com/watch?v=uPEVukOu2-M) for more haha)

Now, theoretically if we just said that the canonical spelling is **𐑛𐑿𐑯**, then people that drop the yod would still drop the yod, and people that say 𐑡 would still say it like that.

Basically, the combination of consonant+yod would be an indicator for many different accents of how to say it.

In fact, 𐑿 being a compound letter seems to indicate that Read thought you would always keep the yod, right?

I believe that this is a different subject from something like 𐑤𐑭𐑕𐑑 vs 𐑤𐑨𐑕𐑑.

Thoughts?

**Comment by Shavian-info** [comment]
I'm not sure what you'd like to change. Are you asking to remove the General American variation from the ReadLex? On this issue I've been following Read who recognised the yodless pronunciations as alternatives. See point 10 in [Read's Guide to Shavian Spelling](https://www.shavian.info/downloads/guide_to_shavian_spelling_1963.pdf).

**Comment by Shavian-info** [comment]
If I understand correctly, in choosing the spelling to list first in the Readlex, I'm basically doing what you suggest. See principle 9 of the [ReadLe xSpelling Principles](https://readlex.pythonanywhere.com/spellingprinciples/).

**Comment by trosel** [comment]
> Are you asking to remove the General American variation from the ReadLex?

I want to discuss the possibility of this, yes. However I think it depends upon the logic of the underlying principles. 

For a trans-atlantic compromise, I think keeping both final Rs and yods is a good idea, orthographically speaking. Shavian keeps final R in the form of compound letters and keeps yod in the form of a compound too. 

Such a thing is placing more emphasis however on the value of a consistent writing system and less importance on accurately representing sound above all else. 

Americans would be taught that they should feel free to pronounce 𐑿 however they see fit given the word. Dune (dropped), cute (kept), dew (dropped) etc.

**Comment by Shavian-info** [comment]
I wonder if we could move this issue to Discussions (if you want to continue talking about it) and close the issue. I see no harm in having the yod-less alternative spellings in the ReadLex for now. Read recognised the alternatives and I already favour the spelling you prefer as the suggested spelling for similar reasons to those you outline.
