### ISSUE TITLE
Clarification on “re-” prefix: 𐑮𐑰- or 𐑮𐑦- ?

### ISSUE THREAD

**Issue by JapanYoshi** [Shavian-info/readlex#31]
I’ve noticed that some of the “re-” words are spelled with 𐑮𐑦 and others spelled with 𐑮𐑰. What are the rules regarding these? I’m guessing that words that put primary or secondary stress on the “re” (e.g. the noun “remake” 𐑮𐑰𐑥𐑱𐑒) and/or words that have a vowel right after the “re” (e.g. reappear 𐑮𐑰𐑩𐑐𐑽) get the 𐑰 spelling, but that doesn’t explain why “rename” gets spelled with 𐑰.

**Comment by Shavian-info** [comment]
It really just follows pronunciation. The prefix 're' is almost always 𐑮𐑰 unless the prefix has become fossilised as part of the word. So to join something again is 𐑮𐑰𐑡𐑶𐑯, but a fancy word for 'answer' is 𐑮𐑦𐑡𐑶𐑯[𐑛𐑼]. Same for repair - if you fix something it's 𐑮𐑦𐑐𐑺, but if you were to pair things again I guess you'd use 𐑮𐑰𐑐𐑺.

**Comment by JapanYoshi** [comment]
Whose pronunciation are we talking about? I personally don’t pronounce “reborn”, “recycle”, “remake”, “remap”, “rename”, “reset”, “reshape”, “reshuffle”, “resize”, or “restate” with 𐑰 as written in the ReadLex.

**Comment by Shavian-info** [comment]
Received Pronunciation, as reflected in modern dictionaries like the Cambridge English Pronouncing Dictionary—see Principle 1 of the [ReadLex Spelling Principles](https://readlex.pythonanywhere.com/spellingprinciples/). Perhaps you could move this to Discussions if you'd like to keep talking about it and close the issue.
