### ISSUE TITLE
Proposed words

### ISSUE THREAD

**Issue by JapanYoshi** [Shavian-info/readlex#33]
Here are some words I tried to use in the game Shingo!, but were not deemed valid words:

    𐑳𐑯𐑕𐑧𐑯𐑑	unsent
    𐑨𐑯𐑑𐑣𐑦𐑤	anthill
    𐑨𐑐𐑤𐑦𐑒𐑱	appliqué
    𐑜𐑳𐑥𐑚𐑷𐑤	gumball
    𐑑𐑴𐑓𐑵	tofu
    𐑑𐑹𐑗𐑑	torched
    𐑑𐑴𐑯𐑼	toner
    𐑒𐑤𐑦𐑑	(untranscribed to prevent text filtering)
    𐑝𐑦𐑛𐑟	vids
    𐑥𐑫𐑖𐑦	mushy (alternate pronunciation)

Thank you for your time!

**Comment by Shavian-info** [comment]
Done.
