### ISSUE TITLE
want and wont

### ISSUE THREAD

**Issue by trosel** [Shavian-info/readlex#4]
The dictionary doesn't have a word for [wont](https://www.merriam-webster.com/dictionary/wont), meaning "accustomed to". Or if it does, then the pronunciation seems to be incorrect.

![image](https://user-images.githubusercontent.com/1299322/151594280-2e52b671-30f3-4948-81a2-ee1f843e58bb.png)

For me, these are my pronunciations:
- want (desire) = 𐑢𐑳𐑯𐑑
- wont (accustomed) = 𐑢𐑪𐑯𐑑
- won't (will not) = 𐑢𐑴𐑯𐑑

Am I missing something here?

**Comment by Shavian-info** [comment]
'Wont' is pronounced /wəʊnt/, and is a homophone for 'won't' in RP. There are quite a few freely available dictionaries with RP pronunciations, such as the Cambridge Dictionary, that let you check things, e.g. [](https://dictionary.cambridge.org/dictionary/english/wont).

**Comment by trosel** [comment]
I do see that the audio pronunciation here matches mine exactly. So it’s odd that Cambridge would ignore that a seemingly significant number of people pronounce it like this https://en.m.wiktionary.org/wiki/wont

I’ve never heard of as a homonym of “won’t” before, but I will defer if that is the most common pronunciation in both England and America
