### ISSUE TITLE
Add Emmett

### ISSUE THREAD

**Issue by Basketcasesoftware** [Shavian-info/readlex#45]
It's literally my middle name and variations of it have been used as the names of famous people. It's also the old English word for an ant. I was rather surprised that it didn't at last try to covert it phonetically.

**Comment by Shavian-info** [comment]
Hi @Basketcasesoftware, this is now done! For something to be converted phonetically, the pronunciation needs to be in the dictionary (which means I have to add the word). Scripts that guess at pronunciation aren't reliable enough for my purposes.
