### ISSUE TITLE
4 names

### ISSUE THREAD

**Issue by paperclone22** [Shavian-info/readlex#47]
I didn't get a translation for these names.
Here's my first attempt from sounding them out with the chart.

```txt
Shannon ·𐑖𐑨𐑯𐑪𐑯
Shelby ·𐑖𐑧𐑤𐑚𐑰
Quinton ·𐑒𐑵𐑾𐑯𐑑𐑪𐑯
Tyson ·𐑑𐑲𐑕𐑳𐑯
```

**Comment by Shavian-info** [comment]
Hi @paperclone22, I've added those names.
