### ISSUE TITLE
Strange heteronym

### ISSUE THREAD

**Issue by rickyweb** [Shavian-info/readlex#48]
When transcribing this:

`John: No, father.`

I get the heteronym "number" <-> "no, father", which doesn't make any sense.

`·𐑡𐑪𐑯: 𐑯𐑳𐑥𐑚𐑼⬌𐑯𐑴, 𐑓𐑭𐑞𐑼.`

Funnily, its not reproducible if you discard John:

`No, father. -> 𐑯𐑴, 𐑓𐑭𐑞𐑼.`

It can be reproduced with another proper name
`Mr Fisher: No, father. -> ·𐑥𐑼 𐑓𐑦𐑖𐑼: 𐑯𐑳𐑥𐑚𐑼⬌𐑯𐑴, 𐑓𐑭𐑞𐑼.`

But not with a non proper word
`answers: no, father -> 𐑭𐑯𐑕𐑼𐑟: 𐑯𐑴, 𐑓𐑭𐑞𐑼.`
`the boy: no, father -> 𐑞 𐑚𐑶: 𐑯𐑴, 𐑓𐑭𐑞𐑼.`

I also get the same phenomenon if I replace father with mother:
`John: No, mother -> ·𐑡𐑪𐑯: 𐑯𐑳𐑥𐑚𐑼⬌𐑯𐑴, 𐑥𐑳𐑞𐑼.`

**Comment by Shavian-info** [comment]
This is because the word 'no' can sometimes stand for 'number', from the word 'numero'. It is, however, an annoyance since the part of speech tagger struggles to distinguish this, and given how rare the 'numero' meaning is, I've just deleted it.
