### ISSUE TITLE
𐑕𐑐𐑦𐑯𐑼 spinner NN1 spɪnəR ?

### ISSUE THREAD

**Issue by JapanYoshi** [Shavian-info/readlex#5]
The compound noun "money-spinner" and "money-spinners" are in the corpus (lines 56466 to 56488 as of now), but just "spinner" and "spinners" are missing.

**Comment by Shavian-info** [comment]
Thanks, I've added 'spinner' and 'spinners'. If you're happy with that, feel free to close the issue.
