### ISSUE TITLE
Missing Word

### ISSUE THREAD

**Issue by adynbrenden** [Shavian-info/readlex#51]
The missing word is queue, queued, queuing.

I suggest the spelling 𐑒𐑿, 𐑒𐑿𐑛, 𐑒𐑿𐑦𐑙 respectively. Albeit the 'if' may be dropped.

**Comment by adynbrenden** [comment]
Just going through my dictionary and typing in all the words under qu; I wanted to know how it would be spelt.

**Comment by Shavian-info** [comment]
Hi @adynbrenden, I think those words are already in the ReadLex, see [queue - ReadLex](https://readlex.pythonanywhere.com/dictionary/queue)

**Comment by adynbrenden** [comment]
Ok, I checked. I was using the converter and it marked it as not existing, but it's working now so must have been a network glitch!

**Comment by mwgamera** [comment]
Actually, there's no _queuing_ only _queueing_. Perhaps that's why it wasn't recognised. Some words have multiple entries with alternative spellings so it might be worth adding that one too, especially since the former spelling seems to be more popular nowadays.

**Comment by adynbrenden** [comment]
It was the spelling suggested by my dictionary.

**Comment by Shavian-info** [comment]
Well spotted both. I'll add the alternative spelling 'queuing' tomorrow.
