### ISSUE TITLE
Triage

### ISSUE THREAD

**Issue by Fugueboy** [Shavian-info/readlex#60]
The word 'triage' seems to be missing from the dictionary. Suggest 𐑑𐑮𐑦𐑭𐑠?

**Comment by JapanYoshi** [comment]
Since "triage" has stress on the first syllable (the only BrE pronunciation and the first AmE pronunciation on Wiktionary), I think it would be 𐑑𐑮𐑰𐑭𐑠. 𐑑𐑮𐑦𐑭𐑠 seems to be an AmE-only variant.
