### ISSUE TITLE
The word "shogi" is missing from the tool.

### ISSUE THREAD

**Issue by Captain-Wet-Beard** [Shavian-info/readlex#63]
I believe this would be spelled "𐑖𐑴𐑜𐑾", please correct me if I'm mistaken.

**Comment by JapanYoshi** [comment]
No, that’d be “Shogia”, ending like “California” and “Libya”.

It would be 𐑖𐑴𐑜𐑦, rhyming with “yogi” (𐑘𐑴𐑜𐑦) https://readlex.pythonanywhere.com/dictionary/yogi

**Comment by Captain-Wet-Beard** [comment]
> No, that’d be “Shogia”, ending like “California” and “Libya”.
> 
> It would be 𐑖𐑴𐑜𐑦, rhyming with “yogi” (𐑘𐑴𐑜𐑦) https://readlex.pythonanywhere.com/dictionary/yogi

Thank you, I appreciate the help
