### ISSUE TITLE
"nerd"

### ISSUE THREAD

**Issue by jdonland** [Shavian-info/readlex#69]
"nerd" and its derivatives like "nerdy" are missing from the lexicon

**Comment by Aethereal-Wraith** [comment]
Suggested spellings (IPA via dictionary.cambridge.org [could only find 2, sorry] and Shavian via my own attempt at transliterating)
nerd - /nɜːd/ - 𐑯𐑻𐑛
nerds - 𐑯𐑻𐑛𐑟
nerdy - /ˈnɜː.di/ - 𐑯𐑻𐑛𐑦
nerdier - 𐑯𐑻𐑛𐑽
nerdiest - 𐑯𐑻𐑛𐑾𐑕𐑑
