### ISSUE TITLE
“tollbooth” spelled with 𐑞 instead of 𐑔

### ISSUE THREAD

**Issue by JapanYoshi** [Shavian-info/readlex#8]

**Comment by Shavian-info** [comment]
The Cambridge Dictionary, which is the primary reference for the ReadLex, gives [/buːð/ as the first pronunciation of 'booth'](https://dictionary.cambridge.org/dictionary/english/booth) which is what I followed, but confusingly [/ˈtɒl.buːθ/ for 'tollbooth](https://dictionary.cambridge.org/dictionary/english/tollbooth)'. It's got to be one or the other. I might go with /buːθ/ which seems more universal across varieties of English.
