### ISSUE TITLE
Missing word 'galliot'

### ISSUE THREAD

**Issue by yttyx** [Shavian-info/readlex#84]
Galliot (𐑜𐑨𐑤𐑦𐑩𐑑)  - a single-masted Dutch cargo boat or fishing vessel.

('Lugger', 'Junk' and 'Schooner' exist in the dictionary.)

**Comment by mwgamera** [comment]
It could be argued that etymologically it's a romance diminutive _galley_ + _-et_, but it seems to have been borrowed in full in both senses. I would write it 𐑜𐑨𐑤𐑾𐑑 with an -𐑾𐑑, even if makes the stress ambiguous. Cf. _chariot_ 𐑗𐑨𐑮𐑾𐑑. (On the other hand, _veriest_ is certainly 𐑝𐑧𐑮𐑦𐑩𐑕𐑑 by Readlex rules.)

**Comment by yttyx** [comment]
Thank you! 𐑜𐑨𐑤𐑾𐑑 is better. And 𐑝𐑧𐑮𐑦𐑩𐑕𐑑 is consistent with 𐑰𐑟𐑦𐑩𐑕𐑑, for example.

**Comment by Shavian-info** [comment]
Added, thanks.
