### ISSUE TITLE
Missing word 'veriest'

### ISSUE THREAD

**Issue by yttyx** [Shavian-info/readlex#85]
Veriest (𐑝𐑧𐑮𐑾𐑕𐑑) - used to emphasize the degree to which a description applies to someone or something.

**Comment by yttyx** [comment]
As [mwgamera suggests](https://github.com/Shavian-info/readlex/issues/84),  𐑝𐑧𐑮𐑦𐑩𐑕𐑑 would be a better spelling, consistent with other Readlex entries.

**Comment by Shavian-info** [comment]
Added, thanks.
