### ISSUE TITLE
"Exponentiation" and other mathematical terms

### ISSUE THREAD

**Issue by PavloSurzh** [Shavian-info/readlex#86]
"Exponent" is in the dictionary, but "exponentiation" is not. There are also lots of other math-related words that are not there, but I'm not sure how relevant they are. For example:

1. Differentiable
2. Integrable
3. Bijection (and bijective)
4. Surjection (and surjective)
5. Injective
6. Cardinality
7. Nilpotent
8. Commutative
9. Rng (not an initialism, pronounced 𐑮𐑳𐑙)
10. Syzygy
11. Clopen (yes, it's a real word)
12. Isomorphism (and isomorphic)
13. Homomorphism
14. Homeomorphism (and homeomorphic)
15. Diffeomorphism (and diffeomorphic)
16. Morphism
17. Epimorphism
18. Monomorphism
19. Bimorphism

When I was looking for missing words that end in "-morphism" I also found that "polymorphic" is there, but "polymorphism" isn't. Also "topology" is in the lexicon, but "topological" and "topologically" aren't.

**Comment by HaleyHalcyon** [comment]
> Rng (not an initialism, pronounced 𐑮𐑳𐑙)

In what field?

**Comment by mwgamera** [comment]
> > Rng (not an initialism, pronounced 𐑮𐑳𐑙)
> 
> In what field?

Algebra, it's a _ring_ without _identity_. I personally never heard it pronounced in English, though.

**Comment by Shavian-info** [comment]
Thanks, I've added these.
