### ISSUE TITLE
“ion” 𐑲𐑪𐑯 but “ions” 𐑲𐑩𐑯𐑟

### ISSUE THREAD

**Issue by HaleyHalcyon** [Shavian-info/readlex#88]
https://readlex.pythonanywhere.com/dictionary/ion
Is this supposed to be inconsistent?

**Comment by Shavian-info** [comment]
No, that's an error. I'll get it on my next update.

**Comment by Shavian-info** [comment]
Both pronunciations appear to be used in the US and UK. I've gone with the 'stronger' pronunciation, 𐑲𐑪𐑯.
